### ISSUE TITLE
Motion view - Polarlight link

### ISSUE THREAD

**Issue by pracine** [odigoteam/odigo-environment-linker#11]
Add a link to polarlight for each destination move (beside produitweb destination).
The url is already present in the configuration file : 
      "moves": [
        {
          "name": "Antargaz",
          "client_id": "ANTAR000",
          "src": "atg01",
          "dest": "atr01",
          "pw_dest": "http://produitweb.prosodie/odigo_cc/odigocc_detail_project.php?appli=atr01&env=p&cluster=w&index=1",
          "id_card": "https://odigocorp.sharepoint.com/:x:/s/Odigo_MOTION-Factory744/ESu0iR-o93hOks5VGr_csXMBcZr4WhA0HWt1bF__yBx5Gg?e=SVKkST",
          "**polarlight**": "https://polarlight.sddc-internal.odigo.cx/web/details.php?id=atr01_w_p_1"
        },
 The target will be available next week.

**Comment by guitaro** [comment]
ok ! Will be included in next release.
