### ISSUE TITLE
pif+pef persistent / 3 ghosts ?

### ISSUE THREAD

**Issue by pracine** [odigoteam/odigo-environment-linker#2]
Les liens pif et pef sont toujours présents dans l'interface d'un client même s'ils sont décochés dans l'interface.

Rien ne change dans l'interface des clients (sur la dizaine (variée) que j'ai testé) que les champs suivants soient cochés ou non :
- hub
- CX Studio
- Qualification Center

**Comment by guitaro** [comment]
Hi @pracine,

Many for reporting 👍.

I'll look for your issue ASAP and will be fixed in the next version.

**Comment by guitaro** [comment]
Unfortunately I can reproduce the issue for Hub, CX Studio and Qualification center. Could you please provide me more details on steps to reproduce ?

**Comment by guitaro** [comment]
I've done a fix in the MR #3  which should resolve the issues. I close the MR and feel free to reopen it if you still have problems.
