### ISSUE TITLE
SSH Link points to wrong machine for ID Cluster 2 (when blue/green mode enabled)

### ISSUE THREAD

**Issue by ycordier-pro** [odigoteam/odigo-environment-linker#27]
When you choose the SSH submenu from the extension on a blue/green environment, for ID Cluster 1 it points the correct machine but for ID Cluster 2 it points to the same as 1 instead of the EC2 name stored in CMDB for that environment number 2.

**Comment by levyndot** [comment]
In fact, the issue was that on click on cluster 2, le cluster 1 and 2 was uncollapsed.
