### ISSUE TITLE
Pif instead of Pef for Public PaaS

### ISSUE THREAD

**Issue by miachella** [odigoteam/odigo-environment-linker#33]
### Description
In the displayed list of tools for any environment, the label for Public PaaS is not correct: "Public PaaS (Pif)" instead of "Public PaaS (Pef)"
![image](https://user-images.githubusercontent.com/65355453/204250440-12db0888-6373-4f8c-ae1e-670c2d830832.png)

### Steps to reproduce
1- Type the beginning of any environment on the search bar
2- Select any env
3- In the displayed list of tools, the label for Public PaaS is not correct

### Technical infos
Extension version : 4.11.0
Git hash : g258ba97

**Comment by levyndot** [comment]
Resovled with Issue #34
