### ISSUE TITLE
Apero page is not disappearing after closing

### ISSUE THREAD

**Issue by miachella** [odigoteam/odigo-environment-linker#5]
![image](https://user-images.githubusercontent.com/65355453/173078190-9968cd7d-a54e-412d-93b9-691158416f70.png)
Voilà, bisous

**Comment by miachella** [comment]
1. Type "/apero" in the search bar
2. Press ctrl + A ad lib
3. Your apero page is doubled, tripled, etc ... 
4. Voilà
5. Bisous

**Comment by guitaro** [comment]
Will be fixed in next release ASAP. Thanks for report 😃
