### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by pracine** [odigoteam/odigo-environment-linker#9]
This is a suggestion of evolution.

Currently, we have the following keywords to configure custom links : 

[aws-account-id] : the Amazon Web Services account ID (12 digits string)
[client-id] : the client ID (AWQ01, SMS01, VKW01, ...)
[client-name] : the complete client name (Air France, Auchan, AESIO, ...)
[client-domain] : the client domain name
[cluster-id] : the cluster ID (1, 2, 3, ...)
[cloud-provider] : the cloud provider (AWS, ODIGO)
[env-type] : the type of environment (dev, int, qa, prod, preprod, prod, odf, ...)
[occ-version] : the odigo CC version (5.4.29, 5.3.38, 5.6.33.1, ...)
[site] : the client site (a...z)
[t-shirt-size] : T-Shirt size of environment (small, medium, large)

We need the short env-type [psqdo] to configure produitweb link, and soon polarlight link.

### Technical infos
Extension version : 4.8.0
Git hash : g12b84b4

**Comment by guitaro** [comment]
Do you know the which CMDB attribute contains this "short env-type" value ?

**Comment by pracine** [comment]
**client_env=p** is the short as **client_environment=prod** is the long one.

**Comment by guitaro** [comment]
Thanks. I'll do it for next release. Thanks.
